apiVersion: v1
kind: Service
metadata:
  name: weather-api-service
  namespace: weather-api-ns
spec:
  selector:
    app: weather-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
